[versions]
accompanist = "0.32.0"
activity-compose = "1.10.1"
activity-ktx = "1.10.1"
androidGradlePlugin = "8.10.1"
androidx-test-ext-junit = "1.2.1"
androidx-window = "1.4.0"
applicationId = "pro.jayeshseth.animations"
cascade = "2.3.0"
coil = "2.7.0"
commonmodule = "0.0.8"
compile-sdk = "36"
compose-bom = "2025.08.01"
compose-compiler = "1.5.0"
core-ktx = "1.17.0"
core-splashscreen = "1.0.1"
coroutines = "1.10.2"
datastore = "1.0.0"
espresso-core = "3.6.1"
junit = "4.13.2"
jvm-target = "17"
kotlin = "2.2.0"
kotlinxSerializationJson = "1.9.0"
ksp = "2.1.20-1.0.31"
lottie = "6.6.6"
lifecycle = "2.6.2"
lifecycle-runtime-ktx = "2.6.1"
material = "1.9.0"
min-sdk = "24"
namespace = "pro.jayeshseth.animations"
navigation = "2.9.0"
navigation-hilt = "1.0.0"
nexusPlugin = "2.0.0"
okhttp = "4.10.0"
palette = "1.0.0"
physicsLayout = "0.4.1"
rebugger = "1.0.0-rc03"
retrofit = "2.9.0"
room = "2.5.2"
spotless = "7.0.3"
target-sdk = "36"
appcompat = "1.7.0"
com-google-android-material-material = "1.12.0"
vanniktechMavenPublish = "0.25.3"
nav3Core = "1.0.0-beta01"
nav3Material = "1.0.0-SNAPSHOT"
nav3Lifecycle = "1.0.0-SNAPSHOT"
kotlinxSerializationCore = "1.9.0"
# versioning
version-code = "10"
version-name = "1.0.7" # X.Y.Z; X = Major, Y = minor, Z = Patch level - (beta, canary) = stage
version-nameBetaSuffix = "-beta01"

[libraries]
# Accompanist
#accompanist-adaptive = { group = "com.google.accompanist", name = "accompanist-adaptive", version.ref = "accompanist" }
#accompanist-drawablePainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }
#accompanist-navigationAnimation = { group = "com.google.accompanist", name = "accompanist-navigation-animation", version.ref = "accompanist" }
#accompanist-navigationMaterial = { group = "com.google.accompanist", name = "accompanist-navigation-material", version.ref = "accompanist" }
#accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
#accompanist-placeHolder = { group = "com.google.accompanist", name = "accompanist-placeholder", version.ref = "accompanist" }
#accompanist-systemUIController = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
#accompanist-testharness = { group = "com.google.accompanist", name = "accompanist-testharness", version.ref = "accompanist" }

# [AndroidX Deps]
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }

# Benchmark

# Cascade
cascade = { group = "me.saket.cascade", name = "cascade", version.ref = "cascade" }
cascade-compose = { group = "me.saket.cascade", name = "cascade-compose", version.ref = "cascade" }

# Coil
coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "coil" }

# Compose
commonmodule = { module = "pro.jayeshseth.madappmodules:commonModules", version.ref = "commonmodule" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material3-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "nav3Material" }
compose-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-googleFonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }

# Core
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
core-splashScreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }

# Coroutines
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }

# Lottie
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

# Navigation
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "nav3Core" }
navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "nav3Core" }


# Palette
palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }

# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }

# Lifecycle
lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "nav3Lifecycle" }

# [Test Dependencies]
# Android Tests
android-test-ext-junit = { group = "androidx.compose.ui", name = "ui-test" }
android-test-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test" }
android-test-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
android-test-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
android-test-navigation = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigation" }

# Unit Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "com-google-android-material-material" }
physics-layout = { module = "io.github.klassenkonstantin:physics-layout", version.ref = "physicsLayout" }
rebugger = { module = "io.github.theapache64:rebugger", version.ref = "rebugger" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
nexus-plugin = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPlugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[bundles]