[versions]
# Build Tools
androidGradlePlugin = "8.10.1"
androidDesugarJdkLibs = "2.1.5"
androidTools = "31.12.0"
ksp = "2.1.20-1.0.31"

# Kotlin
kotlin = "2.2.0"
kotlinxSerializationJson = "1.9.0"
kotlin-coroutines = "1.10.2"
kotlinxSerializationCore = "1.9.0"

# Compose
compose-hot-reload = "1.0.0"
compose-multiplatform = "1.9.0"
compose-jetbrains = "1.8.2"
material-icons = "1.7.3"

# Androidx
activity-compose = "1.10.1"
activity-ktx = "1.10.1"
androidx-test-ext-junit = "1.2.1"
androidx-window = "1.4.0"
androidx-core-ktx = "1.17.0"
datastore = "1.0.0"
core-splashscreen = "1.0.1"
datastorePreferences = "1.2.0"
appcompat = "1.7.0"

# Others
cascade = "2.3.0"
accompanist = "0.37.3"
coil = "3.3.0"
compose-bom = "2025.08.01"
composeCodeEditor = "2.0.3"
espresso-core = "3.6.1"
junit = "4.13.2"
lottie = "6.6.6"
lifecycle = "2.6.2"
lifecycle-runtime-ktx = "2.6.1"
navigation = "2.9.0"
palette = "1.0.0"
physicsLayout = "0.4.1"
rebugger = "1.0.0-rc03"
spotless = "7.0.3"
nav3Core = "1.0.0-beta01"
nav3Material = "1.0.0-SNAPSHOT"
nav3Lifecycle = "1.0.0-SNAPSHOT"
haze = "1.7.1"
hypnoticcanvas = "0.4.1"
composeUnstyled = "1.49.3"

# Versioning
applicationId = "pro.jayeshseth.animations"
namespace = "pro.jayeshseth.animations"
version-code = "10"
version-name = "1.0.8" # X.Y.Z; X = Major, Y = minor, Z = Patch level - (beta, canary) = stage
version-nameBetaSuffix = "-beta01"
jvm-target = "17"
target-sdk = "36"
compile-sdk = "36"
min-sdk = "24"




[libraries]
# Accompanist
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

# [AndroidX Deps]
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferences" }
androidx-window = { module = "androidx.window:window", version.ref = "androidx-window" }

# Benchmark

# Cascade
cascade = { group = "me.saket.cascade", name = "cascade", version.ref = "cascade" }
cascade-compose = { group = "me.saket.cascade", name = "cascade-compose", version.ref = "cascade" }

# Coil
coil-kt = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil" }

# Androidx Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-code-editor = { module = "com.github.qawaz:compose-code-editor", version.ref = "composeCodeEditor" }
compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material3-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "nav3Material" }
compose-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-googleFonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
compose-animation-graphics = { group = "androidx.compose.animation", name = "animation-graphics" }
compose-unstyled = { group = "com.composables", name = "composeunstyled", version.ref = "composeUnstyled" }

# Jetbrains Compose
jetbrains-compose-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose-multiplatform" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-jetbrains" }
jetbrains-compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "compose-jetbrains" }
jetbrains-compose-material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "material-icons" }
jetbrains-compose-material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "material-icons" }
jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-jetbrains" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-jetbrains" }

# Core
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
core-splashScreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }

# Coroutines
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }

# Lottie
lottie = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

# Navigation
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "nav3Core" }
navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "nav3Core" }

hypnoticcanvas = { module = "com.mikepenz.hypnoticcanvas:hypnoticcanvas", version.ref = "hypnoticcanvas" }
hypnoticcanvas-shaders = { module = "com.mikepenz.hypnoticcanvas:hypnoticcanvas-shaders", version.ref = "hypnoticcanvas" }

# Palette
palette = { group = "androidx.palette", name = "palette", version.ref = "palette" }

# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }

# Lifecycle
lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "nav3Lifecycle" }

haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }

# [Test Dependencies]
# Android Tests
android-test-ext-junit = { group = "androidx.compose.ui", name = "ui-test" }
android-test-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test" }
android-test-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
android-test-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
android-test-navigation = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigation" }

# Unit Tests
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
physics-layout = { module = "io.github.klassenkonstantin:physics-layout", version.ref = "physicsLayout" }
rebugger = { module = "io.github.theapache64:rebugger", version.ref = "rebugger" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
spotless-gradlePlugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }


[plugins]
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hot-reload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
androidTest = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }


animations-application = { id = "animations.android.application" }
animations-library = { id = "animations.android.library" }

[bundles]
androidx = [
    "androidx-activity-compose", "androidx-activity-ktx", "androidx-window",
]
compose = [
    "compose-ui", "compose-ui-util", "compose-ui-graphics",
    "compose-ui-tooling", "compose-ui-tooling-preview", "compose-material",
    "compose-material3", "compose-material3-window", "compose-ui-googleFonts",
    "compose-material3-navigation3", "compose-material-iconsExtended"
]
navigation = [
    "navigation-compose", "navigation3-runtime", "navigation3-ui"
]